### PR TITLE
Added support for samc21_xpro; using same openocd target as samd21_xpro

### LINKED ISSUE #92: Support for SAMC21
I'm trying to program an ATSAMC21, but I'm struggling to find the the right header files in pio. All I seem to be able to find is support for the SAMD* series.

I'm new to PlatformIO, so I might well be overlooking something, or does pio not support the SAMC21?

### PR DESCRIPTION
**Pull request by zeroisnan**
Resolve #92 Support for SAMC21 

- Added a new board file for Microchip SAMC21 XplainedPRO board. The OpenOCD target still points to at91samdXX as I could not find a samcXX specific version and could not see anything specific to SAMD which would prevent it to work on SAMC.
- Added SVD file downloaded from the [CMSIS ARM website](https://developer.arm.com/tools-and-software/embedded/cmsis/cmsis-packs)
- Updated all the example files for the mbed framework with the new board

This change was tested with a SAMC21 XplainedPRO board.
I am new to this so I hope I provided all the required information.

### CODE REVIEW

**Comment by zeroisnan** [comment]
Hi,
I see tests with mbed are failing.

I did test the change (build, upload, debug) with a SAMC21 XplainedPRO board, but I am not using any framework (I am importing an AtmeslStart generated framework, but that is another story).

Possible options:
- give me some hints of what is being looked up for the mbed framework and I'll see if I can address this as well
- keep the board definition, but remove the mbed framework from it (and clean up the examples)
- cancel this pull request

Apologies for not having checked this aspect before issuing a pull request

Regards,
nico

**Comment by valeros** [comment]
Hi @zeroisnan ! Thanks for the PR! It looks like this board doesn't support `mbed` framework, so there is no reason to mention it in the board manifest (you can assign an empty list to the `frameworks` filed). For the same reason this board shouldn't have been added to the examples. As for `openocd` target, it should be fine since you correctly specified the `chipname` field.

**Comment by valeros** [comment]
The url `https://developer.mbed.org/platforms/SAMC21-XPRO/` seems broken as well.

**Comment by zeroisnan** [comment]
HI @valeros how is the URL used? If it is for information purposes, I could like the page at Microchip [https://www.microchip.com/DevelopmentTools/ProductDetails/PartNO/ATSAMC21-XPRO](url)

**Comment by valeros** [comment]
https://www.microchip.com/DevelopmentTools/ProductDetails/PartNO/ATSAMC21-XPRO is just what we need.

**Comment by zeroisnan** [comment]
done, let me know if anything else is needed

**Comment by maxgerhardt** [comment]
@zeroisnan, do you have a PlatformIO example project for the chip, presumably using the ASF or Atmel Start framework?

**Pull request merged**
